### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by spookykokojunge** [Sn1ppr/Probin#1]
Hey that code dosent work for me pls help?

**Comment by Sn1ppr** [comment]
Have you configured the variables in the .env correctly?

**Comment by spookykokojunge** [comment]
What are variables ?

**Comment by Sn1ppr** [comment]
![image](https://github.com/Sn1ppr/Probin/assets/97407987/94406522-bc88-46ce-8427-75306db66c3e)

**Comment by spookykokojunge** [comment]
Whats that what am i supposed to put in there ?
